name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:  [{cron: '0 * * * *'}]
    
  push:
    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master"]
    
  workflow_dispatch:
  
jobs:
  github-metrics:
     runs-on: ubuntu-latest
     environment: 
      name: shubhanshu
     permissions:
      contents: write
     steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SHUBHANSHU_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
          
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata

          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
                    
          
         


